Settings:
  max_history: 7  # 最多保留最近7天的文章
  load_images: true  # 是否加载图片
  filename_template: "生活{date}.epub"  # 自定义文件名模板
  # 可用占位符:
  # {year} - 年份 (2025)
  # {month} - 月份 (07)
  # {day} - 日期 (04)
  # {hour} - 小时 (14)
  # {minute} - 分钟 (30)
  # {second} - 秒 (45)
  # {date} - 中文日期 (2025年7月4日)
  # {time} - 中文时间 (14时30分)
  # {datetime} - 中文日期时间 (2025年7月4日_14时30分)
  # 示例: "RSS精选_{date}.epub" → "RSS精选_2025年7月4日.epub"

Feeds:
  # 示例1: 使用CSS选择器提取内容
  - url: "https://sspai.com/feed"
    name: "少数派"
    title: "少数派精选"
    enabled: true
    resolve_link:
      enabled: true
      method: "selector"  # 优先使用选择器
      selectors:
        content: "article, .post-content, .article-content, main"  # 内容选择器
        remove: ".ads, .comments, .related-posts, script, style"  # 要移除的元素
      fallback: "readability"  # 选择器失败时使用readability

  # 示例2: 直接使用readability自动提取
  - url: "https://rsshub.app/cma/channel/380"
    name: "中国气象局"
    title: "每日天气提示"
    enabled: true
    resolve_link:
      enabled: true
      method: "readability"  # 直接使用readability

  # 示例3: 不解析原始链接，使用RSS摘要
  - url: "https://rsshub.app/ifanr/index"
    name: "爱范儿"
    title: "爱范儿"
    enabled: true
    resolve_link:
      enabled: true
      method: "readability" 

-url: "https://rsshub.app/chsi/kydt"
    name: "中国研究生招生信息网"
    title: "考研动态"
    enabled: true
    resolve_link:
      enabled: true
      method: "readability"  

-url: "https://rsshub.app/neea/local/ntce"
    name: "中国教育考试网"
    title: "教资考试动态"
    enabled: true
    resolve_link:
      enabled: true
      method: "readability"  

-url: "https://rsshub.app/bjnews/cat/depth"
    name: "新京报"
    title: "文化"
    enabled: true
    resolve_link:
      enabled: true
      method: "readability"  
