#!/bin/bash
# 设置定时任务示例脚本

echo "RSS to Kindle 定时推送设置"
echo "=========================="
echo ""
echo "以下是一些定时任务示例，你可以使用 crontab -e 添加："
echo ""
echo "# 每天早上7点推送"
echo "0 7 * * * cd /Users/haleyc/vscode/RSS && /usr/bin/python3 rss_and_send.py >> cron_log.txt 2>&1"
echo ""
echo "# 每天早上7点和晚上7点推送（一天两次）"
echo "0 7,19 * * * cd /Users/haleyc/vscode/RSS && /usr/bin/python3 rss_and_send.py >> cron_log.txt 2>&1"
echo ""
echo "# 每周一、三、五早上8点推送"
echo "0 8 * * 1,3,5 cd /Users/haleyc/vscode/RSS && /usr/bin/python3 rss_and_send.py >> cron_log.txt 2>&1"
echo ""
echo "# 每周日晚上9点推送周刊"
echo "0 21 * * 0 cd /Users/haleyc/vscode/RSS && /usr/bin/python3 rss_and_send.py >> cron_log.txt 2>&1"
echo ""
echo "设置步骤："
echo "1. 运行 crontab -e 编辑定时任务"
echo "2. 复制上面的任务行（根据需要修改时间）"
echo "3. 保存并退出"
echo "4. 运行 crontab -l 查看已设置的任务"
echo ""
echo "注意事项："
echo "- 确保 email_config.yaml 已正确配置"
echo "- 确保 Python 路径正确（可用 which python3 查看）"
echo "- 日志会保存在 cron_log.txt 中"